"""Build the inert public ComfyUI Workbench preview. Standard library only."""
from __future__ import annotations

import argparse
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
WEB = ROOT / "src" / "comfyui_py_workflow" / "web"
DOCS = ROOT / "docs"


def render_local_index() -> str:
    shell = (WEB / "index.html").read_text(encoding="utf-8")
    marker = "<!-- COMFYUI_BATCH -->"
    if shell.count(marker) != 1:
        raise ValueError("Local UI must contain exactly one COMFYUI_BATCH marker")
    return shell.replace(marker, (WEB / "batch.html").read_text(encoding="utf-8"))


def preview_html() -> str:
    html = render_local_index()
    html = html.replace(
        "<!doctype html>",
        "<!doctype html>\n<!-- Generated by scripts/build_ui_preview.py; edit the local UI or preview sources. -->",
    )
    html = html.replace(
        '<link rel="stylesheet" href="/static/style.css">',
        '''<meta name="description" content="ComfyUI Workbench 批量图片与首尾帧视频静态预览。使用虚构文件名，无上传或模型请求。">
  <meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'self'; style-src 'self'; img-src 'self' data:; media-src 'self'; connect-src 'none'; form-action 'none'; base-uri 'none'">
  <link rel="stylesheet" href="style.css">
  <link rel="stylesheet" href="preview.css">''',
    )
    html = html.replace(
        "<body>",
        '''<body>
  <div class="preview-notice"><strong>界面预览</strong><span>虚构配对示例 · 无上传、模型或后台连接</span><a href="https://github.com/marsguo2049/comfyui-py-workflow#quick-start">在本机运行 ↗</a></div>
  <noscript><p class="no-script">请启用 JavaScript 切换批量工具。真正处理任务请在本机运行项目。</p></noscript>''',
    )
    html = re.sub(r'  <script src="/static/[^"\n]+"></script>\n', "", html)
    html = html.replace("</body>", '  <script src="preview.js"></script>\n</body>')
    html = re.sub(r'<(input|textarea|select)\b', r'<\1 disabled', html)
    html = html.replace('<select disabled id="batch-tool">', '<select id="batch-tool">')

    def disable_action(match: re.Match[str]) -> str:
        tag = match.group(0)
        return tag if "data-view=" in tag or 'id="go-settings"' in tag else tag.replace("<button", "<button disabled", 1)

    html = re.sub(r"<button\b[^>]*>", disable_action, html)
    html = html.replace('<span id="service-summary">检测中</span>', '<span id="service-summary">仅展示</span>')
    html = html.replace('<article class="status-card" id="comfy-status"><strong>ComfyUI</strong><p>尚未检测</p></article>',
                        '<article class="status-card" id="comfy-status"><strong>ComfyUI</strong><p>预览模式，不检测本机服务。</p></article>')
    html = html.replace('在本机处理与保存<small>', '公开虚构示例<small>')
    html = html.replace('批量任务留在本机。</span>', '静态预览 · 实际任务请在本机运行。</span>')
    html = html.replace('<option value="first-last-video">', '<option value="first-last-video" selected>')
    html = html.replace('<div id="batch-video-inputs" class="hidden">', '<div id="batch-video-inputs">')
    html = html.replace('<div id="batch-drop" class="drop-zone">', '<div id="batch-drop" class="drop-zone hidden">')
    html = html.replace(
        '<div id="batch-pair-preview" class="selection-list" aria-live="polite"></div>',
        '''<div id="batch-pair-preview" class="selection-list" aria-live="polite">
                <div class="selection-row">1. sample-start-01.png → sample-end-01.png</div>
                <div class="selection-row">2. sample-start-02.png → sample-end-02.png</div>
              </div>''',
    )
    html = html.replace('<strong id="batch-first-count">尚未选择</strong>', '<strong id="batch-first-count">已选择 2 张 · 示例</strong>')
    html = html.replace('<strong id="batch-last-count">尚未选择</strong>', '<strong id="batch-last-count">已选择 2 张 · 示例</strong>')
    html = html.replace('<p id="batch-duration-hint" class="hint"></p>', '<p id="batch-duration-hint" class="hint">预计每段 5.17 秒 · 125 帧 / 24 fps · 共 2 段</p>')
    return html


def overview_svg() -> str:
    return '''<svg xmlns="http://www.w3.org/2000/svg" width="1440" height="900" viewBox="0 0 1440 900" role="img" aria-labelledby="title desc">
<title id="title">ComfyUI Workbench batch video overview</title>
<desc id="desc">A static illustration of first and last frame pairing in the ComfyUI Workbench.</desc>
<rect width="1440" height="900" fill="#f7f8fa"/>
<rect x="0" y="0" width="224" height="900" fill="#fff"/>
<rect x="24" y="32" width="38" height="38" rx="11" fill="#525ce5"/>
<text x="35" y="59" fill="#fff" font-size="24" font-family="Segoe UI, sans-serif">C</text>
<text x="76" y="51" fill="#202733" font-size="18" font-weight="700" font-family="Segoe UI, sans-serif">ComfyUI Workbench</text>
<text x="76" y="70" fill="#707887" font-size="12" font-family="Segoe UI, sans-serif">本地批量工作台</text>
<rect x="18" y="137" width="188" height="48" rx="8" fill="#eef0ff"/>
<text x="45" y="168" fill="#525ce5" font-size="16" font-family="Segoe UI, sans-serif">▦　批量工具</text>
<text x="45" y="218" fill="#707887" font-size="16" font-family="Segoe UI, sans-serif">⚙　ComfyUI 设置</text>
<text x="264" y="76" fill="#707887" font-size="13" font-family="Segoe UI, sans-serif">BATCH TOOLS</text>
<text x="264" y="123" fill="#202733" font-size="34" font-weight="700" font-family="Segoe UI, sans-serif">一次设定，批量完成。</text>
<text x="264" y="156" fill="#707887" font-size="15" font-family="Segoe UI, sans-serif">批量修改图片，或用首尾帧生成视频。</text>
<rect x="264" y="205" width="1116" height="620" rx="12" fill="#fff" stroke="#e3e6ec"/>
<text x="292" y="250" fill="#202733" font-size="20" font-weight="700" font-family="Segoe UI, sans-serif">批量首尾帧视频</text>
<rect x="292" y="282" width="500" height="190" rx="10" fill="#fafbff" stroke="#cdd1e7"/>
<rect x="820" y="282" width="500" height="190" rx="10" fill="#fafbff" stroke="#cdd1e7"/>
<text x="320" y="322" fill="#202733" font-size="18" font-weight="700" font-family="Segoe UI, sans-serif">首帧</text>
<text x="848" y="322" fill="#202733" font-size="18" font-weight="700" font-family="Segoe UI, sans-serif">尾帧</text>
<text x="320" y="370" fill="#707887" font-size="15" font-family="Segoe UI, sans-serif">sample-start-01.png</text>
<text x="848" y="370" fill="#707887" font-size="15" font-family="Segoe UI, sans-serif">sample-end-01.png</text>
<text x="320" y="410" fill="#707887" font-size="15" font-family="Segoe UI, sans-serif">sample-start-02.png</text>
<text x="848" y="410" fill="#707887" font-size="15" font-family="Segoe UI, sans-serif">sample-end-02.png</text>
<text x="292" y="526" fill="#202733" font-size="17" font-weight="700" font-family="Segoe UI, sans-serif">配对预览</text>
<rect x="292" y="550" width="1028" height="54" rx="8" fill="#f7f8fa"/>
<text x="316" y="583" fill="#505866" font-size="15" font-family="Segoe UI, sans-serif">1. sample-start-01.png → sample-end-01.png</text>
<rect x="292" y="616" width="1028" height="54" rx="8" fill="#f7f8fa"/>
<text x="316" y="649" fill="#505866" font-size="15" font-family="Segoe UI, sans-serif">2. sample-start-02.png → sample-end-02.png</text>
<text x="292" y="715" fill="#707887" font-size="14" font-family="Segoe UI, sans-serif">预计每段 5.17 秒 · 125 帧 / 24 fps · 共 2 段</text>
<rect x="1110" y="745" width="210" height="44" rx="8" fill="#525ce5"/>
<text x="1142" y="773" fill="#fff" font-size="15" font-weight="700" font-family="Segoe UI, sans-serif">开始批量处理 →</text>
<text x="264" y="865" fill="#9299a7" font-size="12" font-family="Segoe UI, sans-serif">界面示意 · 虚构文件名 · 无后台连接</text>
</svg>
'''


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    artifacts = {
        DOCS / "index.html": preview_html(),
        DOCS / "style.css": (WEB / "style.css").read_text(encoding="utf-8"),
        DOCS / "assets" / "comfyui-workbench-preview.svg": overview_svg(),
    }
    stale = []
    for path, content in artifacts.items():
        if args.check:
            existing = path.read_text(encoding="utf-8") if path.is_file() else None
            if existing != content:
                stale.append(path.relative_to(ROOT).as_posix())
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
    if stale:
        parser.exit(1, "Preview is stale; run python scripts/build_ui_preview.py: " + ", ".join(stale) + "\n")
    print("Public UI preview is up to date." if args.check else "Built public UI preview.")


if __name__ == "__main__":
    main()
